source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'ARNetwork_Example' do
    pod 'ARNetwork', :path => '../'

    target 'ARNetwork_Tests' do
        inherit! :search_paths

        pod 'Specta'
        pod 'Expecta'
    end
end
