source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'ARNetwork_Example' do
    pod 'ARNetwork', :subspecs => ['Default', 'Cache/Swift'], :path => '../'

    #CocoaPods does not currently support subspecs across different build configurations.
	#pod 'ARNetwork/Mock', :configurations => ['Debug'], :path => '../'
	pod 'ARNetwork/Mock', :path => '../'

    target 'ARNetwork_Tests' do
        inherit! :search_paths

        pod 'Specta'
        pod 'Expecta'
    end
end
