source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

platform :ios, '8.0'

use_frameworks!

target 'ARNetwork_Example' do
    pod 'ARNetwork', :path => '../'

    target 'ARNetwork_Tests' do
        inherit! :search_paths

        pod 'Specta'
        pod 'Expecta'
    end
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
